[workspace]
members = ["crates/server", "crates/cairo1-run", "crates/tracer"]
resolver = "2"

[workspace.package]
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[workspace.dependencies]
axum = "0.6.20"
tower = "0.4.13"
tower-http = { version = "0.4.4", features = ["cors", "trace"] }
tokio = { version = "1.33.0", features = ["full"] }
serde = { version = "1.0.163", features = ["derive"] }
serde_json = "1.0.104"
url = "2.4.0"
rand = "0.8.5"

cairo-vm = { git = "https://github.com/walnuthq/cairo-vm.git", rev = "80f28818ac342f9be21100fa9a472f2de424e9a4", features = [
    "cairo-1-hints",
] }
cairo-lang-compiler = { git = "https://github.com/walnuthq/cairo", rev = "3a0c51b5198de61be415e847c7e9b968d0897cc6" }
cairo-lang-sierra = { git = "https://github.com/walnuthq/cairo", rev = "3a0c51b5198de61be415e847c7e9b968d0897cc6" }
cairo-lang-sierra-type-size = { git = "https://github.com/walnuthq/cairo", rev = "3a0c51b5198de61be415e847c7e9b968d0897cc6" }
cairo-lang-sierra-to-casm = { git = "https://github.com/walnuthq/cairo", rev = "3a0c51b5198de61be415e847c7e9b968d0897cc6" }
cairo-lang-sierra-ap-change = { git = "https://github.com/walnuthq/cairo", rev = "3a0c51b5198de61be415e847c7e9b968d0897cc6" }
cairo-lang-sierra-gas = { git = "https://github.com/walnuthq/cairo", rev = "3a0c51b5198de61be415e847c7e9b968d0897cc6" }
cairo-lang-sierra-generator = { git = "https://github.com/walnuthq/cairo", rev = "3a0c51b5198de61be415e847c7e9b968d0897cc6" }
cairo-lang-casm = { git = "https://github.com/walnuthq/cairo", rev = "3a0c51b5198de61be415e847c7e9b968d0897cc6" }
cairo-lang-utils = { git = "https://github.com/walnuthq/cairo", rev = "3a0c51b5198de61be415e847c7e9b968d0897cc6" }

thiserror = "1.0.56"
bincode = { version = "2.0.0-rc.3", default-features = false, features = [
    "serde",
] }
itertools = "0.12.0"
