networks:
  app-network:

services:
  app:
    build: .
    expose:
      - 3000
    networks:
      - app-network

  nginx:
    restart: unless-stopped
    image: nginx:latest
    container_name: nginx
    volumes:
      - ./docker-volumes/nginx/conf:/etc/nginx/conf.d:rw
      - ./docker-volumes/nginx/vhost:/etc/nginx/vhost.d
      - ./docker-volumes/nginx/html:/usr/share/nginx/html
      - ./docker-volumes/nginx/certs:/usr/certs/:ro
      - /etc/letsencrypt/live/api2.cairovm.codes:/certs/live/api2.cairovm.codes:ro
      - /etc/letsencrypt/archive:/certs/archive:ro
    networks:
      - app-network
    ports:
      - 443:443