[package]
name = "cairo1-run"
version.workspace = true
edition.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow.workspace = true
serde.workspace = true
serde_json.workspace = true
cairo-vm.workspace = true
cairo-lang-compiler.workspace = true
cairo-lang-sierra.workspace = true
cairo-lang-sierra-type-size.workspace = true
cairo-lang-sierra-to-casm.workspace = true
cairo-lang-sierra-ap-change.workspace = true
cairo-lang-sierra-gas.workspace = true
cairo-lang-sierra-generator.workspace = true
cairo-lang-starknet.workspace = true
cairo-lang-runner.workspace = true
cairo-lang-casm.workspace = true
cairo-lang-utils.workspace = true
cairo-lang-diagnostics.workspace = true
cairo-lang-test-plugin.workspace = true
cairo-lang-filesystem.workspace = true
thiserror.workspace = true
bincode.workspace = true
itertools.workspace = true
starknet-types-core.workspace = true
