[package]
name = "cairo1-run"
version.workspace = true
edition.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cairo-vm.workspace = true
cairo-lang-compiler.workspace = true
cairo-lang-sierra.workspace = true
cairo-lang-sierra-type-size.workspace = true
cairo-lang-sierra-to-casm.workspace = true
cairo-lang-sierra-ap-change.workspace = true
cairo-lang-sierra-gas.workspace = true
cairo-lang-sierra-generator.workspace = true
cairo-lang-casm.workspace = true
cairo-lang-utils.workspace = true
thiserror.workspace = true
bincode.workspace = true
itertools.workspace = true
